wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.15.8
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1697704875.447542
    t:
      1:
      - 1
      - 41
      - 55
      - 71
      3:
      - 23
      4: 3.10.12
      5: 0.15.8
      8:
      - 5
